test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -221,57 +221,68 @@ deploy_to_test:
     curl -s --data-binary "@$(ls -A1 /root/helm_package/)" $CHART_API_URI/api/$1/charts
   }
 
-   function install_tiller() {
+  function install_tiller() {
 
-      #kubectl create -n "$TILLER_NAMESPACE"
-      #kubectl create namespace "$TILLER_NAMESPACE"
+    #kubectl create -n "$TILLER_NAMESPACE"
+    #kubectl create namespace "$TILLER_NAMESPACE"
 
-      echo "Creating Tiller Service Account for namespace ${TILLER_NAMESPACE}"
-      cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
-      apiVersion: v1
-      kind: ServiceAccount
-      metadata:
+    echo "Creating Tiller Service Account for namespace ${TILLER_NAMESPACE}"
+    cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
+    apiVersion: v1
+    kind: ServiceAccount
+    metadata:
+      name: tiller
+  EOF
+
+    echo "Creating Tiller Role for namespace ${TILLER_NAMESPACE}"
+    cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
+    kind: Role
+    apiVersion: rbac.authorization.k8s.io/v1beta1
+    metadata:
+      name: tiller-manager
+    rules:
+      - apiGroups: ["", "extensions", "apps"]
+        resources: ["*"]
+        verbs: ["*"]
+  EOF
+
+    echo "Creating Tiller RoleBinding for namespace ${TILLER_NAMESPACE}"
+    cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
+    kind: RoleBinding
+    apiVersion: rbac.authorization.k8s.io/v1beta1
+    metadata:
+      name: tiller-binding
+    subjects:
+      - kind: ServiceAccount
         name: tiller
-    EOF
-
-      echo "Creating Tiller Role for namespace ${TILLER_NAMESPACE}"
-      cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
+    roleRef:
       kind: Role
-      apiVersion: rbac.authorization.k8s.io/v1beta1
-      metadata:
-        name: tiller-manager
-      rules:
-        - apiGroups: ["", "extensions", "apps"]
-          resources: ["*"]
-          verbs: ["*"]
-    EOF
-
-      echo "Creating Tiller RoleBinding for namespace ${TILLER_NAMESPACE}"
-      cat | kubectl apply -n "$TILLER_NAMESPACE" -f - << EOF
-      kind: RoleBinding
-      apiVersion: rbac.authorization.k8s.io/v1beta1
-      metadata:
-        name: tiller-binding
-      subjects:
-        - kind: ServiceAccount
-          name: tiller
-      roleRef:
-        kind: Role
-        name: tiller-manager
-        apiGroup: rbac.authorization.k8s.io
-    EOF
+      name: tiller-manager
+      apiGroup: rbac.authorization.k8s.io
+  EOF
 
 
-      echo "Checking Tiller..."
-      helm init --upgrade --service-account "tiller" --tiller-namespace "$TILLER_NAMESPACE" --tiller-image acr2.tst.apnic.net/asdf/kubernetes-helm/tiller:v2.8.0
-      kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
-      if ! helm version --debug; then
-        echo "Failed to init Tiller."
-        return 1
-      fi
-      echo ""
-    }
+    echo "Checking Tiller..."
+    helm init --upgrade --service-account "tiller" --tiller-namespace "$TILLER_NAMESPACE" --tiller-image acr2.tst.apnic.net/asdf/kubernetes-helm/tiller:v2.8.0
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
+    echo ""
+  }
 
+  function create_secret() {
+    echo "Create secret..."
+
+    kubectl create secret -n "$KUBE_NAMESPACE" \
+      docker-registry gitlab-registry \
+      --docker-server="$CI_REGISTRY" \
+      --docker-username="$CI_REGISTRY_USER" \
+      --docker-password="$CI_REGISTRY_PASSWORD" \
+      --docker-email="$GITLAB_USER_EMAIL" \
+      -o yaml --dry-run | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
+  }
 
 before_script:
   - *auto_devops
